### ISSUE TITLE
您好，请教一下如果想在按钮上加售罄或者库存紧张的状态标识该怎么修改呢？

### ISSUE THREAD

**Issue by whatisjava** [wp529/SkuAlgorithm#1]
您好，请教一下如果想在按钮上加售罄或者库存紧张的状态标识该怎么修改呢？如下图所示
![WX20221213-182244@2x](https://user-images.githubusercontent.com/366992/207292477-2a644b85-a949-428f-9986-1959345a2e13.png)

**Comment by wp529** [comment]
sorry，才看到，这个需求与sku算法没关系，只需要在你定义的规格上新增一个字段标记状态，根据状态展示对应标识即可。
